### ISSUE TITLE
More information about the scrip

### ISSUE THREAD

**Issue by ojdas** [keptenkurk/Check_flights#1]
Could please help me resolve this:
/data/aircraft.json
I don't see any additional directory in your script?
Could you please help me to implement?

Thanks,
Piotr

**Comment by keptenkurk** [comment]
Not sure if i understand the question right.. feel free to get into more detail where needed.
The http://<ip>/dump1090/data/aircraft.json will reply with a json object with the current location of all planes in view, like:
'''
{
now: 1461823241.2,
messages: 303037649,
aircraft: [
{
hex: "4841d8",
squawk: "2153",
lat: 51.759201,
lon: 4.384733,
nucp: 5,
seen_pos: 6.1,
altitude: 10425,
vert_rate: 3136,
track: 182,
speed: 280,
messages: 4,
seen: 6.1,
rssi: -33.7
},
{
hex: "44a838",
squawk: "0103",
flight: "JAF4791 ",
lat: 50.951797,
lon: 4.119725,
nucp: 7,
seen_pos: 0.7,
altitude: 23200,
vert_rate: 2368,
track: 112,
speed: 454,
messages: 86,
seen: 0.3,
rssi: -32.3
},
'''
You must use the dump1090-mutability version found at https://github.com/mutability/dump1090 and details of the json's are here https://github.com/mutability/dump1090/blob/master/README-json.md.
Depending on the configuration of the webserver (i use an external one) your dump1090-mutab data will be served on port 8080 or 80. If this script runs on the same host as dump1090-mutab than localhost 127.0.0.1 can be used as ip.
Rest of the script is reading the json and recording positions of interest regarding lattitude, longitude and height,

**Comment by ojdas** [comment]
Thanks for the info now all is clear however I didn't receive any emails from Google.
Configuration seems fine from my side but no emails.
Do you have any idea?

Thanks,
Piotr

**Comment by keptenkurk** [comment]
@ojdas Did you manage to get an xml file with at least 6 positions? Does the mailing generate errors? I use the same mailing code also in https://github.com/keptenkurk/BS440/blob/master/BS440mail.py no problems there either...

**Comment by ojdas** [comment]
@keptenkurk How to manage XML file? Probably this is an issue...

**Comment by keptenkurk** [comment]
Well, the XML file will _only_ be generated if an aircraft crosses your area of interest: A square defined to be between low and high lattitude (lowlat, hilat) and low and high longitude (lowlon, hilon). Also aircraft should be below hialt (high altitude in feet), as i'm not interested in aircraft flying over at 30000 ft or so.
Every aircraft with position(s) within this box will leave an XML file in the current folder named like icao_date_time.gpx like "3b777b_160420_1554.gpx" containing all the positions.
Only if this XML file contains at least 6 positions it will be sent by email.

The whole idea behind this script is that i wanted to check if commercial aircraft really would avoid certain areas due to noise restrictions as promised. The result is: they don't...

**Comment by ojdas** [comment]
@keptenkurk Hmm I don't know why my XML file is not generated. Maybe my configuration is not correct. How you define square of lat/long ? Could you please describe?

**Comment by keptenkurk** [comment]
@ojdas It's in the start of the code:
'# Area of interest
lowlat   = 51.456833
hilat    = 51.479605
lowlon  = 5.238706
hilon   = 5.275276
hialt    = 8200

Longitude and Lattilude can be looked up with google maps. Just point to a location and get the coordinates from the URL (like: https://www.google.nl/maps/@53.3313801,6.3797224,5.92z) for 53.3313801 lattitude and 6.3797224 longitude.
Not sure what your area of interest would be and if we run into trouble with Easter/Western hemisphere or Northern vs Southern... It works like described for the eastern/northern part of our planet.

**Comment by ojdas** [comment]
@keptenkurk I have tried in many different ways but script it doesn't work for me :( as well as I have no idea why. I don't receive any errors when I run script so there is no background to debug where is the issue.

**Comment by keptenkurk** [comment]
@ojdas Although willing to, it is very hard for me to help you like this. Additional debugging can be easily provided by adding some print statements yourself. So i will close the issue.
